--- 
abstract: read-eval-print-loop for debugging your Catalyst application
author: 
  - Tomas Doram <bobtfish@bobtfish.net>
  - Florian Ragwitz <rafl@debian.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: CatalystX-REPL
requires: 
  Carp::REPL: 0
  Catalyst: 5.800006
  namespace::clean: 0
version: 0.01
